name: Build and deploy frontend
on:
    workflow_dispatch:
    push:
        branches:
            main
        paths:
            frontend/**

jobs: 
    build-and-deploy-frontend:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: eu-west-2

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                node-version: latest
                cache: npm

            - name: Remove not needed module
              run: rm -r infra
            
            - name: Install dependencies
              run: npm i

            - name: Build frontend
              run: npm run build -w frontend
            
            - name: Upload build to S3 
              run: aws s3 sync ./frontend/dist/ s3://geo-reference-tool-frontend-build-bucket --delete

            - name: Invalidate Cloudfront
              run: aws cloudfront create-invalidation --distribution-id E1V2Z057YTE16A --paths '/*'